base_url = "https://blog.thecount.eu.org"
title = "thecountrox"
description = "Tech, Linux, Devops and Programming"
compile_sass = true
minify_html = true
author = "Prajol David"
generate_feeds = true
build_search_index = true
feed_filenames = ["rss.xml", "atom.xml"]

default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

# aliases = []
# slug = "blog"
[markdown]
header_ids = "enabled"
render_emoji = true
external_links_target_blank = true
highlight_code = true
highlight_theme = "ayu-dark"
smart_punctuation = true
bottom_footnotes = true

[extra]
default_theme = "dark"

index_format = "fuse_json"

nav.links = [
    { name = "home", url = "/" },
    { name = "blog", url = "/blog" },
    { name = "tags", url = "/tags" },
    { name = "portfolio", url = "https://github.com/thecountrox/" },
]

show_copy_button = true
show_reading_time = true
show_share_button = true

nav.auto_hide = false
nav.show_theme_switcher = true
nav.show_feed = true
nav.show_repo = true
show_backlinks = true

source_url = "https://git.thecount.eu.org/thecountrox/blog"
go_to_top = true
toc_sidebar = true

taxonomies = [{ name = "tags", rss = true }, { name = "categories" }]
